// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbw3lfURy5akhEfFL3eJlJwDwnd5Q7EF0',
    appId: '1:737285632088:web:4b63c537821fda9a0d1a2d',
    messagingSenderId: '737285632088',
    projectId: 'aplimovil-final',
    authDomain: 'aplimovil-final.firebaseapp.com',
    databaseURL: 'https://aplimovil-final-default-rtdb.firebaseio.com',
    storageBucket: 'aplimovil-final.appspot.com',
    measurementId: 'G-ZCPY8XNGN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArtdijndEk8osWsRVHu9j-dYgOaNjl0zk',
    appId: '1:737285632088:android:e4d711a4a8de36eb0d1a2d',
    messagingSenderId: '737285632088',
    projectId: 'aplimovil-final',
    databaseURL: 'https://aplimovil-final-default-rtdb.firebaseio.com',
    storageBucket: 'aplimovil-final.appspot.com',
  );
}
